server:
  port: 8002
spring:
  application:
    name: sca-login
  datasource:
    #url: jdbc:mysql://localhost:3306/mysql-generator?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&autoReconnect=true&serverTimezone=UTC
    url: jdbc:mysql://127.0.0.1:3306/mysql-generator?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
